### ISSUE TITLE
Add 'version' command

### ISSUE THREAD

**Issue by haadcode** [haadcode/orbit-db-cli#4]
There should be a command 'version' which displays the version of the binary. 

The version number should be read from package.json. 

The user would run `orbitdb version` and the output should be one line and display the version number.

**Comment by prabodhmeshram** [comment]
Hi @haadcode, I could take a stab on this.

**Comment by haadcode** [comment]
@prabodhmeshram absolutely! Thanks you for jumping in ❤️ 

Take a look at the commands in `src/commands/` for a reference, perhaps `id` is a good example.

What you should do is add `version.js` to `src/commands/` and put everything in that one file. It'd be great to have one test for this (just to make sure it return the right version number and works). See ` test/` for a test example.

Is that enough for you to get started?

**Comment by haadcode** [comment]
@prabodhmeshram note that I just merged a new version to master, you should use that as your starting point.

**Comment by prabodhmeshram** [comment]
Sure @haadcode, Thanks for the info. Well I did forked the repo and started to look into the application structure. I tried to install the cli through npm and github as mentioned in the readme, but it failed for me.

**Below is the error when installing from npm:**

```
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout fix/default-filename
npm ERR! error: pathspec 'fix/default-filename' did not match any file(s) known to git.
npm ERR! 

```

**Below is the error when installing from github:**

```
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git checkout 356c9e9d162a8148e7946db51121ea9d468c4f48
npm ERR! fatal: reference is not a tree: 356c9e9d162a8148e7946db51121ea9d468c4f48
npm ERR! 

``` 


```
My system Specs:
OS : Ubuntu 14.04
Node : v8.1.0
Npm : 5.0.3
```
Am I doing something wrong. Can you please guide me on this. Let me know If I am missing something. Thanks for your help

**Comment by prabodhmeshram** [comment]
Npm install worked for me after I took the latest changes from the repo.

**Comment by haadcode** [comment]
This was done by @prabodhmeshram in https://github.com/haadcode/orbit-db-cli/pull/5. 

Thank you for contributing! 🎉
